// Copyright (c) 2007-2010 SlimDX Group
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//------------------------------------------------------------------------------
// <auto-generated>
//     Enums for SlimDX2.DirectSound namespace.
//     This code was generated by a tool.
//     Date : 11/15/2010 14:52:48
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SlimDX2.DirectSound {

    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSOUND_ENUM_0</unmanaged>
    public enum SoundEffectResult : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_PRESENT</unmanaged>
        Present = unchecked((int)0),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_LOCHARDWARE</unmanaged>
        LocatedInHardware = unchecked((int)1),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_LOCSOFTWARE</unmanaged>
        LocatedInSoftware = unchecked((int)2),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_UNALLOCATED</unmanaged>
        Unallocated = unchecked((int)3),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_FAILED</unmanaged>
        Failed = unchecked((int)4),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_UNKNOWN</unmanaged>
        Unknown = unchecked((int)5),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFXR_SENDLOOP</unmanaged>
        FxrSendloop = unchecked((int)6),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSOUND_ENUM_1</unmanaged>
    public enum I3DL2MaterialPreset : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_SINGLEWINDOW</unmanaged>
        Singlewindow = unchecked((int)0),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_DOUBLEWINDOW</unmanaged>
        Doublewindow = unchecked((int)1),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_THINDOOR</unmanaged>
        Thindoor = unchecked((int)2),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_THICKDOOR</unmanaged>
        Thickdoor = unchecked((int)3),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_WOODWALL</unmanaged>
        Woodwall = unchecked((int)4),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_BRICKWALL</unmanaged>
        Brickwall = unchecked((int)5),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_STONEWALL</unmanaged>
        Stonewall = unchecked((int)6),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_MATERIAL_PRESET_CURTAIN</unmanaged>
        Curtain = unchecked((int)7),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSOUND_ENUM_2</unmanaged>
    public enum I3DL2ReverbPreset : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_DEFAULT</unmanaged>
        Default = unchecked((int)0),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_GENERIC</unmanaged>
        Generic = unchecked((int)1),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_PADDEDCELL</unmanaged>
        PaddedCell = unchecked((int)2),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_ROOM</unmanaged>
        Room = unchecked((int)3),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_BATHROOM</unmanaged>
        Bathroom = unchecked((int)4),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_LIVINGROOM</unmanaged>
        LivingRoom = unchecked((int)5),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_STONEROOM</unmanaged>
        StoneRoom = unchecked((int)6),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_AUDITORIUM</unmanaged>
        Auditorium = unchecked((int)7),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_CONCERTHALL</unmanaged>
        ConcertHall = unchecked((int)8),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_CAVE</unmanaged>
        Cave = unchecked((int)9),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_ARENA</unmanaged>
        Arena = unchecked((int)10),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_HANGAR</unmanaged>
        Hangar = unchecked((int)11),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_CARPETEDHALLWAY</unmanaged>
        CarpetedHallway = unchecked((int)12),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_HALLWAY</unmanaged>
        Hallway = unchecked((int)13),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_STONECORRIDOR</unmanaged>
        StoneCorridor = unchecked((int)14),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_ALLEY</unmanaged>
        Alley = unchecked((int)15),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_FOREST</unmanaged>
        Forest = unchecked((int)16),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_CITY</unmanaged>
        City = unchecked((int)17),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_MOUNTAINS</unmanaged>
        Mountains = unchecked((int)18),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_QUARRY</unmanaged>
        Quarry = unchecked((int)19),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_PLAIN</unmanaged>
        Plain = unchecked((int)20),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_PARKINGLOT</unmanaged>
        ParkingLot = unchecked((int)21),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_SEWERPIPE</unmanaged>
        SewerPipe = unchecked((int)22),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_UNDERWATER</unmanaged>
        Underwater = unchecked((int)23),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_SMALLROOM</unmanaged>
        SmallRoom = unchecked((int)24),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_MEDIUMROOM</unmanaged>
        MediumRoom = unchecked((int)25),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_LARGEROOM</unmanaged>
        LargeRoom = unchecked((int)26),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_MEDIUMHALL</unmanaged>
        MediumHall = unchecked((int)27),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_LARGEHALL</unmanaged>
        LargeHall = unchecked((int)28),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSFX_I3DL2_ENVIRONMENT_PRESET_PLATE</unmanaged>
        Plate = unchecked((int)29),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSCAPS_FLAGS</unmanaged>
    [Flags]
    public enum CapabilitiesFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_PRIMARYMONO</unmanaged>
        PrimaryBufferMono = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_PRIMARYSTEREO</unmanaged>
        PrimaryBufferStereo = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_PRIMARY8BIT</unmanaged>
        PrimaryBuffer8Bit = unchecked((int)0x00000004),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_PRIMARY16BIT</unmanaged>
        PrimaryBuffer16Bit = unchecked((int)0x00000008),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_CONTINUOUSRATE</unmanaged>
        ContinousRate = unchecked((int)0x00000010),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_EMULDRIVER</unmanaged>
        EmulatedDriver = unchecked((int)0x00000020),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_CERTIFIED</unmanaged>
        Certified = unchecked((int)0x00000040),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_SECONDARYMONO</unmanaged>
        SecondaryBufferMono = unchecked((int)0x00000100),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_SECONDARYSTEREO</unmanaged>
        SecondaryBufferStereo = unchecked((int)0x00000200),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_SECONDARY8BIT</unmanaged>
        SecondaryBufer8Bit = unchecked((int)0x00000400),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCAPS_SECONDARY16BIT</unmanaged>
        SecondaryBufer16Bit = unchecked((int)0x00000800),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSSPEAKER_ENUM</unmanaged>
    public enum SpeakerConfiguration : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_DIRECTOUT</unmanaged>
        DirectOut = unchecked((int)0x00000000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_HEADPHONE</unmanaged>
        Headphone = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_MONO</unmanaged>
        Mono = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_QUAD</unmanaged>
        Quadrophonic = unchecked((int)0x00000003),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_STEREO</unmanaged>
        Stereo = unchecked((int)0x00000004),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_SURROUND</unmanaged>
        Surround = unchecked((int)0x00000005),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_5POINT1</unmanaged>
        FivePointOne = unchecked((int)0x00000006),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_7POINT1</unmanaged>
        SevenPointOne = unchecked((int)0x00000007),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_7POINT1_SURROUND</unmanaged>
        SevenPointOneSurround = unchecked((int)0x00000008),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_5POINT1_SURROUND</unmanaged>
        FivePointOneSurround = unchecked((int)0x00000009),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_7POINT1_WIDE</unmanaged>
        SevenPointOneWide = unchecked((int)SevenPointOne),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_5POINT1_BACK</unmanaged>
        FivePointOneBack = unchecked((int)FivePointOne),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSSPEAKER_GEOMETRY_ENUM</unmanaged>
    public enum SpeakerGeometry : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_GEOMETRY_MIN</unmanaged>
        Minimum = unchecked((int)0x00000005),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_GEOMETRY_NARROW</unmanaged>
        Narrow = unchecked((int)0x0000000A),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_GEOMETRY_WIDE</unmanaged>
        Wide = unchecked((int)0x00000014),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSPEAKER_GEOMETRY_MAX</unmanaged>
        Maximum = unchecked((int)0x000000B4),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSBCAPS_FLAGS</unmanaged>
    [Flags]
    public enum BufferFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_PRIMARYBUFFER</unmanaged>
        PrimaryBuffer = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_STATIC</unmanaged>
        Static = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_LOCHARDWARE</unmanaged>
        Hardware = unchecked((int)0x00000004),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_LOCSOFTWARE</unmanaged>
        Software = unchecked((int)0x00000008),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRL3D</unmanaged>
        Control3D = unchecked((int)0x00000010),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRLFREQUENCY</unmanaged>
        ControlFrequency = unchecked((int)0x00000020),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRLPAN</unmanaged>
        ControlPan = unchecked((int)0x00000040),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRLVOLUME</unmanaged>
        ControlVolume = unchecked((int)0x00000080),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRLPOSITIONNOTIFY</unmanaged>
        ControlPositionNotify = unchecked((int)0x00000100),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_CTRLFX</unmanaged>
        ControlEffects = unchecked((int)0x00000200),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_STICKYFOCUS</unmanaged>
        StickyFocus = unchecked((int)0x00004000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_GLOBALFOCUS</unmanaged>
        GlobalFocus = unchecked((int)0x00008000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_GETCURRENTPOSITION2</unmanaged>
        GetCurrentPosition2 = unchecked((int)0x00010000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_MUTE3DATMAXDISTANCE</unmanaged>
        Mute3DAtMaxDistance = unchecked((int)0x00020000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_LOCDEFER</unmanaged>
        Defer = unchecked((int)0x00040000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBCAPS_TRUEPLAYPOSITION</unmanaged>
        Trueplayposition = unchecked((int)0x00080000),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSBPLAY_FLAGS</unmanaged>
    [Flags]
    public enum PlayFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_LOOPING</unmanaged>
        Looping = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_LOCHARDWARE</unmanaged>
        Hardware = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_LOCSOFTWARE</unmanaged>
        Software = unchecked((int)0x00000004),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_TERMINATEBY_TIME</unmanaged>
        TerminateByTime = unchecked((int)0x00000008),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_TERMINATEBY_DISTANCE</unmanaged>
        TerminateByDistance = unchecked((int)0x000000010),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBPLAY_TERMINATEBY_PRIORITY</unmanaged>
        TerminateByPriority = unchecked((int)0x000000020),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSBSTATUS_FLAGS</unmanaged>
    [Flags]
    public enum BufferStatus : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_PLAYING</unmanaged>
        Playing = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_BUFFERLOST</unmanaged>
        BufferLost = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_LOOPING</unmanaged>
        Looping = unchecked((int)0x00000004),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_LOCHARDWARE</unmanaged>
        Hardware = unchecked((int)0x00000008),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_LOCSOFTWARE</unmanaged>
        Software = unchecked((int)0x00000010),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBSTATUS_TERMINATED</unmanaged>
        Terminated = unchecked((int)0x00000020),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSCBCAPS_FLAGS</unmanaged>
    [Flags]
    public enum CaptureBufferCapabilitiesFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCBCAPS_WAVEMAPPED</unmanaged>
        Wavemapped = unchecked((int)0x80000000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCBCAPS_CTRLFX</unmanaged>
        Ctrlfx = unchecked((int)0x00000200),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSCCAPS_FLAGS</unmanaged>
    [Flags]
    public enum CaptureCapabilitiesFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCCAPS_EMULDRIVER</unmanaged>
        EmulateDriver = unchecked((int)CapabilitiesFlags.EmulatedDriver),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCCAPS_CERTIFIED</unmanaged>
        Certified = unchecked((int)CapabilitiesFlags.Certified),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCCAPS_MULTIPLECAPTURE</unmanaged>
        MultipleCapture = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// None.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSBLOCK_ENUM</unmanaged>
    public enum LockFlags : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBLOCK_FROMWRITECURSOR</unmanaged>
        FromWriteCursor = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSBLOCK_ENTIREBUFFER</unmanaged>
        EntireBuffer = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>None</unmanaged>
        None = unchecked((int)0),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSSCL_ENUM</unmanaged>
    public enum CooperativeLevel : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSCL_NORMAL</unmanaged>
        Normal = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSCL_PRIORITY</unmanaged>
        Priority = unchecked((int)0x00000002),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSCL_EXCLUSIVE</unmanaged>
        Exclusive = unchecked((int)0x00000003),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSSCL_WRITEPRIMARY</unmanaged>
        WritePrimary = unchecked((int)0x00000004),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DS3DMODE</unmanaged>
    public enum Mode3D : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DS3DMODE_NORMAL</unmanaged>
        Normal = unchecked((int)0x00000000),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DS3DMODE_HEADRELATIVE</unmanaged>
        HeadRelative = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DS3DMODE_DISABLE</unmanaged>
        Disable = unchecked((int)0x00000002),			
    }
    
    /// <summary>	
    /// No documentation.	
    /// </summary>	
    /// <unmanaged>DSCFX_ENUM</unmanaged>
    public enum CaptureEffectResult : int {	
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCFX_LOCHARDWARE</unmanaged>
        LocatedInHardware = unchecked((int)0x00000001),			
        
        /// <summary>	
        /// No documentation.	
        /// </summary>	
        /// <unmanaged>DSCFX_LOCSOFTWARE</unmanaged>
        LocatedInSoftware = unchecked((int)0x00000002),			
    }
}
