// Copyright (c) 2007-2010 SlimDX Group
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
namespace Boost.Wave
{
    public enum TokenId : uint
    {
        Unknown = 0,
        FirstToken = 256,
        And = FirstToken | TokenCategory.OperatorTokenType,
        AndAlt = FirstToken | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        Andand = 257 | TokenCategory.OperatorTokenType,
        AndandAlt = 257 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        Assign = 258 | TokenCategory.OperatorTokenType,
        Andassign = 259 | TokenCategory.OperatorTokenType,
        AndassignAlt = 259 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        Or = 260 | TokenCategory.OperatorTokenType,
        OrAlt = 260 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        OrTrigraph = 260 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Orassign = 261 | TokenCategory.OperatorTokenType,
        OrassignAlt = 261 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        OrassignTrigraph = 261 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Xor = 262 | TokenCategory.OperatorTokenType,
        XorAlt = 262 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        XorTrigraph = 262 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Xorassign = 263 | TokenCategory.OperatorTokenType,
        XorassignAlt = 263 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        XorassignTrigraph = 263 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Comma = 264 | TokenCategory.OperatorTokenType,
        Colon = 265 | TokenCategory.OperatorTokenType,
        Divide = 266 | TokenCategory.OperatorTokenType,
        Divideassign = 267 | TokenCategory.OperatorTokenType,
        Dot = 268 | TokenCategory.OperatorTokenType,
        Dotstar = 269 | TokenCategory.OperatorTokenType,
        Ellipsis = 270 | TokenCategory.OperatorTokenType,
        Equal = 271 | TokenCategory.OperatorTokenType,
        Greater = 272 | TokenCategory.OperatorTokenType,
        Greaterequal = 273 | TokenCategory.OperatorTokenType,
        Leftbrace = 274 | TokenCategory.OperatorTokenType,
        LeftbraceAlt = 274 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        LeftbraceTrigraph = 274 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Less = 275 | TokenCategory.OperatorTokenType,
        Lessequal = 276 | TokenCategory.OperatorTokenType,
        Leftparen = 277 | TokenCategory.OperatorTokenType,
        Leftbracket = 278 | TokenCategory.OperatorTokenType,
        LeftbracketAlt = 278 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        LeftbracketTrigraph = 278 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Minus = 279 | TokenCategory.OperatorTokenType,
        Minusassign = 280 | TokenCategory.OperatorTokenType,
        Minusminus = 281 | TokenCategory.OperatorTokenType,
        Percent = 282 | TokenCategory.OperatorTokenType,
        Percentassign = 283 | TokenCategory.OperatorTokenType,
        Not = 284 | TokenCategory.OperatorTokenType,
        NotAlt = 284 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        Notequal = 285 | TokenCategory.OperatorTokenType,
        NotequalAlt = 285 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        Oror = 286 | TokenCategory.OperatorTokenType,
        OrorAlt = 286 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        OrorTrigraph = 286 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Plus = 287 | TokenCategory.OperatorTokenType,
        Plusassign = 288 | TokenCategory.OperatorTokenType,
        Plusplus = 289 | TokenCategory.OperatorTokenType,
        Arrow = 290 | TokenCategory.OperatorTokenType,
        Arrowstar = 291 | TokenCategory.OperatorTokenType,
        QuestionMark = 292 | TokenCategory.OperatorTokenType,
        Rightbrace = 293 | TokenCategory.OperatorTokenType,
        RightbraceAlt = 293 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        RightbraceTrigraph = 293 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Rightparen = 294 | TokenCategory.OperatorTokenType,
        Rightbracket = 295 | TokenCategory.OperatorTokenType,
        RightbracketAlt = 295 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        RightbracketTrigraph = 295 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        ColonColon = 296 | TokenCategory.OperatorTokenType,
        Semicolon = 297 | TokenCategory.OperatorTokenType,
        Shiftleft = 298 | TokenCategory.OperatorTokenType,
        Shiftleftassign = 299 | TokenCategory.OperatorTokenType,
        Shiftright = 300 | TokenCategory.OperatorTokenType,
        Shiftrightassign = 301 | TokenCategory.OperatorTokenType,
        Star = 302 | TokenCategory.OperatorTokenType,
        Compl = 303 | TokenCategory.OperatorTokenType,
        ComplAlt = 303 | TokenCategory.OperatorTokenType | TokenCategory.AltExtTokenType,
        ComplTrigraph = 303 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Starassign = 304 | TokenCategory.OperatorTokenType,
        Asm = 305 | TokenCategory.KeywordTokenType,
        Auto = 306 | TokenCategory.KeywordTokenType,
        Bool = 307 | TokenCategory.KeywordTokenType,
        False = 308 | TokenCategory.BoolLiteralTokenType,
        True = 309 | TokenCategory.BoolLiteralTokenType,
        Break = 310 | TokenCategory.KeywordTokenType,
        Case = 311 | TokenCategory.KeywordTokenType,
        Catch = 312 | TokenCategory.KeywordTokenType,
        Char = 313 | TokenCategory.KeywordTokenType,
        Class = 314 | TokenCategory.KeywordTokenType,
        Const = 315 | TokenCategory.KeywordTokenType,
        Constcast = 316 | TokenCategory.KeywordTokenType,
        Continue = 317 | TokenCategory.KeywordTokenType,
        Default = 318 | TokenCategory.KeywordTokenType,
        Delete = 319 | TokenCategory.KeywordTokenType,
        Do = 320 | TokenCategory.KeywordTokenType,
        Double = 321 | TokenCategory.KeywordTokenType,
        Dynamiccast = 322 | TokenCategory.KeywordTokenType,
        Else = 323 | TokenCategory.KeywordTokenType,
        Enum = 324 | TokenCategory.KeywordTokenType,
        Explicit = 325 | TokenCategory.KeywordTokenType,
        Export = 326 | TokenCategory.KeywordTokenType,
        Extern = 327 | TokenCategory.KeywordTokenType,
        Float = 328 | TokenCategory.KeywordTokenType,
        For = 329 | TokenCategory.KeywordTokenType,
        Friend = 330 | TokenCategory.KeywordTokenType,
        Goto = 331 | TokenCategory.KeywordTokenType,
        If = 332 | TokenCategory.KeywordTokenType,
        Inline = 333 | TokenCategory.KeywordTokenType,
        Int = 334 | TokenCategory.KeywordTokenType,
        Long = 335 | TokenCategory.KeywordTokenType,
        Mutable = 336 | TokenCategory.KeywordTokenType,
        Namespace = 337 | TokenCategory.KeywordTokenType,
        New = 338 | TokenCategory.KeywordTokenType,
        Operator = 339 | TokenCategory.KeywordTokenType,
        Private = 340 | TokenCategory.KeywordTokenType,
        Protected = 341 | TokenCategory.KeywordTokenType,
        Public = 342 | TokenCategory.KeywordTokenType,
        Register = 343 | TokenCategory.KeywordTokenType,
        Reinterpretcast = 344 | TokenCategory.KeywordTokenType,
        Return = 345 | TokenCategory.KeywordTokenType,
        Short = 346 | TokenCategory.KeywordTokenType,
        Signed = 347 | TokenCategory.KeywordTokenType,
        Sizeof = 348 | TokenCategory.KeywordTokenType,
        Static = 349 | TokenCategory.KeywordTokenType,
        Staticcast = 350 | TokenCategory.KeywordTokenType,
        Struct = 351 | TokenCategory.KeywordTokenType,
        Switch = 352 | TokenCategory.KeywordTokenType,
        Template = 353 | TokenCategory.KeywordTokenType,
        This = 354 | TokenCategory.KeywordTokenType,
        Throw = 355 | TokenCategory.KeywordTokenType,
        Try = 356 | TokenCategory.KeywordTokenType,
        Typedef = 357 | TokenCategory.KeywordTokenType,
        Typeid = 358 | TokenCategory.KeywordTokenType,
        Typename = 359 | TokenCategory.KeywordTokenType,
        Union = 360 | TokenCategory.KeywordTokenType,
        Unsigned = 361 | TokenCategory.KeywordTokenType,
        Using = 362 | TokenCategory.KeywordTokenType,
        Virtual = 363 | TokenCategory.KeywordTokenType,
        Void = 364 | TokenCategory.KeywordTokenType,
        Volatile = 365 | TokenCategory.KeywordTokenType,
        Wchart = 366 | TokenCategory.KeywordTokenType,
        While = 367 | TokenCategory.KeywordTokenType,
        PpDefine = 368 | TokenCategory.PPTokenType,
        PpIf = 369 | TokenCategory.PPConditionalTokenType,
        PpIfdef = 370 | TokenCategory.PPConditionalTokenType,
        PpIfndef = 371 | TokenCategory.PPConditionalTokenType,
        PpElse = 372 | TokenCategory.PPConditionalTokenType,
        PpElif = 373 | TokenCategory.PPConditionalTokenType,
        PpEndif = 374 | TokenCategory.PPConditionalTokenType,
        PpError = 375 | TokenCategory.PPTokenType,
        PpLine = 376 | TokenCategory.PPTokenType,
        PpPragma = 377 | TokenCategory.PPTokenType,
        PpUndef = 378 | TokenCategory.PPTokenType,
        PpWarning = 379 | TokenCategory.PPTokenType,
        Identifier = 380 | TokenCategory.IdentifierTokenType,
        Octalint = 381 | TokenCategory.IntegerLiteralTokenType,
        Decimalint = 382 | TokenCategory.IntegerLiteralTokenType,
        Hexaint = 383 | TokenCategory.IntegerLiteralTokenType,
        Intlit = 384 | TokenCategory.IntegerLiteralTokenType,
        Longintlit = 385 | TokenCategory.IntegerLiteralTokenType,
        Floatlit = 386 | TokenCategory.FloatingLiteralTokenType,
        Fixedpointlit = 386 | TokenCategory.FloatingLiteralTokenType | TokenCategory.AltTokenType, // IDL specific
        Ccomment = 387 | TokenCategory.WhiteSpaceTokenType | TokenCategory.AltTokenType,
        Cppcomment = 388 | TokenCategory.WhiteSpaceTokenType | TokenCategory.AltTokenType,
        Charlit = 389 | TokenCategory.CharacterLiteralTokenType,
        Stringlit = 390 | TokenCategory.StringLiteralTokenType,
        Contline = 391 | TokenCategory.EOLTokenType,
        Space = 392 | TokenCategory.WhiteSpaceTokenType,
        Space2 = 393 | TokenCategory.WhiteSpaceTokenType,
        Newline = 394 | TokenCategory.EOLTokenType,
        Generatednewline = 394 | TokenCategory.EOLTokenType | TokenCategory.AltTokenType,
        PoundPound = 395 | TokenCategory.OperatorTokenType,
        PoundPoundAlt = 395 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        PoundPoundTrigraph = 395 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Pound = 396 | TokenCategory.OperatorTokenType,
        PoundAlt = 396 | TokenCategory.OperatorTokenType | TokenCategory.AltTokenType,
        PoundTrigraph = 396 | TokenCategory.OperatorTokenType | TokenCategory.TriGraphTokenType,
        Any = 397 | TokenCategory.UnknownTokenType,
        AnyTrigraph = 397 | TokenCategory.UnknownTokenType | TokenCategory.TriGraphTokenType,
        PpInclude = 398 | TokenCategory.PPTokenType,
        PpQheader = 399 | TokenCategory.PPTokenType,
        PpHheader = 400 | TokenCategory.PPTokenType,
        PpIncludeNext = 398 | TokenCategory.PPTokenType | TokenCategory.AltTokenType,
        PpQheaderNext = 399 | TokenCategory.PPTokenType | TokenCategory.AltTokenType,
        PpHheaderNext = 400 | TokenCategory.PPTokenType | TokenCategory.AltTokenType,
        Eof = 401 | TokenCategory.EOFTokenType, // end of file reached
        Eoi = 402 | TokenCategory.EOFTokenType, // end of input reached
        PpNumber = 403 | TokenCategory.InternalTokenType,
        //msextensions	=	// MS extensions
        MsextInt8 = 404 | TokenCategory.KeywordTokenType,
        MsextInt16 = 405 | TokenCategory.KeywordTokenType,
        MsextInt32 = 406 | TokenCategory.KeywordTokenType,
        MsextInt64 = 407 | TokenCategory.KeywordTokenType,
        MsextBased = 408 | TokenCategory.KeywordTokenType,
        MsextDeclspec = 409 | TokenCategory.KeywordTokenType,
        MsextCdecl = 410 | TokenCategory.KeywordTokenType,
        MsextFastcall = 411 | TokenCategory.KeywordTokenType,
        MsextStdcall = 412 | TokenCategory.KeywordTokenType,
        MsextTry = 413 | TokenCategory.KeywordTokenType,
        MsextExcept = 414 | TokenCategory.KeywordTokenType,
        MsextFinally = 415 | TokenCategory.KeywordTokenType,
        MsextLeave = 416 | TokenCategory.KeywordTokenType,
        MsextInline = 417 | TokenCategory.KeywordTokenType,
        MsextAsm = 418 | TokenCategory.KeywordTokenType,

        MsextPpRegion = 419 | TokenCategory.PPTokenType,
        MsextPpEndregion = 420 | TokenCategory.PPTokenType,

        //importisneededtobeakeywordforthec++modulestandardsproposal	=	// import is needed to be a keyword for the C++ module Standards proposal
        Import = 421 | TokenCategory.KeywordTokenType,

        LastTokenId,
        LastToken = LastTokenId & ~TokenCategory.TokenTypeMask,

        //pseudotokenstohelpstreamliningmacroreplacement,theseshouldnot	=	// pseudo tokens to help streamlining macro replacement, these should not 
        //returnedfromthelexernorshouldthesebereturnedfromthepp-iterator	=	// returned from the lexer nor should these be returned from the pp-iterator
        NonreplacableIdentifier = (LastToken + 1) | TokenCategory.IdentifierTokenType,
        Placeholder = (LastToken + 2) | TokenCategory.WhiteSpaceTokenType,
        Placemarker = (LastToken + 3) | TokenCategory.InternalTokenType,
        Parameterbase = (LastToken + 4) | TokenCategory.ParameterTokenType,
        Extparameterbase = (LastToken + 4) | TokenCategory.ExtParameterTokenType
    }
}