// Copyright (c) 2007-2010 SlimDX Group
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// --------------------------------------------------------------------------------
// Generator for SlimDX2.Error assembly
// Dump All known errors from DXGetErrorString
// --------------------------------------------------------------------------------
#include "stdafx.h"

#include <Windows.h>
#include <DxErr.h>

#include <time.h>

const char* fileTemplateHeader = 
"// Copyright (c) 2007-2010 SlimDX Group\n"
"// \n"
"// Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"// of this software and associated documentation files (the \"Software\"), to deal\n"
"// in the Software without restriction, including without limitation the rights\n"
"// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"// copies of the Software, and to permit persons to whom the Software is\n"
"// furnished to do so, subject to the following conditions:\n"
"// \n"
"// The above copyright notice and this permission notice shall be included in\n"
"// all copies or substantial portions of the Software.\n"
"// \n"
"// THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
"// THE SOFTWARE.\n"
"\n"
"//------------------------------------------------------------------------------\n"
"// <auto-generated>\n"
"//     ErrorMessages for SlimDX2.Error assembly.\n"
"//     This code was generated by a tool.\n"
"//     Date : %s\n"
"//\n"
"//     Changes to this file may cause incorrect behavior and will be lost if\n"
"//     the code is regenerated.\n"
"// </auto-generated>\n"
"//------------------------------------------------------------------------------\n"
"using System;\n"
"\n"
"namespace SlimDX2\n"
"{\n"
"    public partial class ErrorManager\n"
"    {\n"
"        static void InitDefaultErrors()\n"
"        {\n";

const char* fileTemplateFooter = 
"        }\n"
"    }\n"
"}\n";

int _tmain(int argc, _TCHAR* argv[])
{
	FILE* fout = fopen("..\\..\\..\\Sources\\SlimDX2.Error\\ErrorMessages.cs","w+");


	// Get datatime in string format
    time_t t;
    time(&t);
    char dateTimeStr[0x100];
	dateTimeStr[0] = 0;
    ctime_s(dateTimeStr, 0x100, &t);

	// Print header
	fprintf(fout, fileTemplateHeader, dateTimeStr);

	for(unsigned int i = 0x00000000; i < 0xFFFFFFFF; i++) {
		const char* errorString = DXGetErrorString(i);
		const char* errorDescription = DXGetErrorDescription(i);

		if ( (i & 0xFFFFF) == 0 ) {
			printf("Parsing error 0x%08X\n",i);
		}

		if ( strcmp(errorString, "Unknown") != 0 ) {
			if (strcmp(errorDescription,"n/a") == 0 ) {
				errorDescription = "";
			}
			fprintf(fout, "            Add(0x%08X, \"%s\", \"%s\");\n",i, errorString, errorDescription);
		}
	}
	// Print footer
	fprintf(fout, fileTemplateFooter);
	fclose(fout);

	return 0;
}

